import { IProject } from "../models/IProject";

export const projects: IProject[] = [
  {
    id: 1,
    name: "Advaantics",
    role: "Full Stack Developer",
    skills: [
      "Node.js",
      "Typescript",
      "Angular",
      "PostgreSQL",
      "Tauri",
      "Nexe",
      "Docker",
      "LRU Cache",
      "WebSockets",
      "MQTT",
    ],
    client: "SIEMENS",
    points: [
      "Reduced setup time by 35% by leading the development of a web app for machine monitoring, integrating OPC UA and Siemens FOCUS servers.",
      "Boosted data operations by 40% by designing a scalable, multi-service backend architecture with Node.js, enhancing machine data management.",
      "Cut data lag by 60% with real-time WebSocket synchronization and MQTT integration for seamless machine interactions.",
      "Increased monitoring efficiency by 70% by implementing LRU cache for time-series data and machine sessions.",
      "Delivered 15+ production builds using Docker, Tauri, and Nexe, streamlining deployments and executable packaging.",
    ],
    link: "",
  },
  {
    id: 2,
    name: "IGBT Health App",
    role: "Full Stack Developer",
    skills: [
      "Node.js",
      "Express",
      "Typescript",
      "React",
      "Zustand",
      "InfluxDB",
      "React Charts",
      "Docker",
      "Python",
    ],
    client: "SIEMENS",
    points: [
      "Led full-stack development, delivering the app in 4 months from scratch to production with 10+ POCs and 3+ user testing builds.",
      "Designed a lean microservice architecture that cut monitoring time by 40% and enhanced predictive accuracy by 25%.",
      "Reduced API response times by 30% by optimizing backend communication and using Zustand for efficient state management.",
      "Improved deployment efficiency by 50% using Docker for containerized builds and delivering the final product with Nexe.",
      "Implemented algorithmic services for real-time performance analysis, boosting data processing and reducing downtime by 20%.",
    ],
    link: "",
  },
  {
    id: 3,
    name: "Google Customer Experience",
    role: "Full Stack Developer",
    skills: [
      "Node.js",
      "Express",
      "PostgreSQL",
      "GCP",
      "Microservices",
      "Monolithic Architecture",
      "Nexe",
      "Docker",
    ],
    client: "Google",
    points: [
      "Developed all backend APIs from scratch, integrating with GCP buckets and implementing custom role management.",
      "Boosted application performance by 50% by transitioning from monolithic to microservice architecture, earning MVP awards.",
      "Increased system reliability by 40% by optimizing PostgreSQL queries and enhancing the application’s scalability.",
      "Contributed to GCP deployment, improving availability and ensuring smooth operation for marketing managers.",
      "Streamlined deployment using Docker, ensuring quick and reliable production builds.",
    ],
    link: "https://www.accenture.com/in-en/services/software-platforms/accenture-google-cloud-business-group",
  },
  {
    id: 4,
    name: "CHUBB: Mergers & Acquisitions",
    role: "Full Stack Developer",
    skills: [
      "Node.js",
      "Express",
      "Angular",
      "PostgreSQL",
      "Azure",
      "Custom Algorithms",
      "Docker",
    ],
    client: "CHUBB",
    points: [
      "Enhanced application infrastructure using Node.js, improving performance by 40% and scalability by 50%.",
      "Reduced deployment times by 35% using Azure for seamless production transitions, lowering operational costs by 20%.",
      "Optimized UI/UX by building responsive Angular components, boosting user engagement by 20% and improving interface usability by 30%.",
      "Implemented custom algorithms to automate deal review processes, enhancing efficiency for brokers and reducing manual efforts.",
      "Fixed critical bugs left by previous developers, ensuring smooth operations and on-time feature delivery.",
    ],
    link: "https://www.chubb.com/us-en/business-insurance/industries/mergers-acquisitions-insurance.html",
  },
];
