import type { Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: 1,
    name: ".comNext",
    role: "Full Stack Engineer",
    skills: [
      "Next.js",
      "TypeScript",
      "Node.js",
      "AWS",
      "WebSockets",
    ],
    client: "AUTODESK",
    employerKey: "autodesk",
    timeline: "Jan 2025 – Present",
    points: [
      "Migrated 100+ webpages across Autodesk domains from static React/Angular/Vue implementations to a Contentful-driven architecture.",
      "Improved page load performance by 15–30% through content optimization, asset handling improvements, code splitting, and build optimization.",
      "Increased Lighthouse performance scores from 60–70 to 80–90 using SSR, React Server Components, lazy loading, and CloudFront CDN.",
      "Contributed to SEO growth from 1M to 5M+ monthly page views while supporting backend, asset, CORS, and migration workflows across 5 microservices.",
    ],
    link: "",
  },
  {
    id: 2,
    name: "MVP Learn v2",
    role: "Full Stack Engineer",
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Deno",
      "Redis",
      "AWS",
    ],
    client: "AUTODESK",
    employerKey: "autodesk",
    timeline: "Dec 2024 – Dec 2025",
    points: [
      "Built 30+ features including custom courses, Zoom/Teams integration, instant support sessions, and student-teacher roadmap workflows.",
      "Designed and implemented a hybrid course architecture (schema, APIs, WebSockets, auth-aware flows) adopted platform-wide.",
      "Implemented Redis-based caching and queue-based scheduling, improving performance by 15–30%.",
      "Drove 50% initial user engagement growth, sustained 5–10% quarterly growth, and 15% increase in course creation.",
    ],
    link: "",
  },
  {
    id: 3,
    name: "IGBT Health App",
    role: "Full Stack Developer",
    skills: [
      "Node.js",
      "Express",
      "React",
      "Zustand",
      "InfluxDB",
      "Docker",
    ],
    client: "SIEMENS",
    employerKey: "siemens",
    points: [
      "Led development of a scalable industrial monitoring system, reducing monitoring time by 40%.",
      "Improved API performance and data handling through microservices, MQTT integration, and optimized frontend state management.",
    ],
    link: "",
  },
  {
    id: 4,
    name: "Advaantics",
    role: "Full Stack Developer",
    skills: [
      "Node.js",
      "Express",
      "Angular",
      "WebSockets",
      "MQTT",
      "Nexe",
    ],
    client: "SIEMENS",
    employerKey: "siemens",
    points: [
      "Built a web-based industrial monitoring platform with real-time synchronization and multi-service backend architecture.",
      "Improved setup time, data operations, and reporting efficiency through OPCUA/FOCUS integrations and performance optimizations.",
    ],
    link: "",
  },
  {
    id: 5,
    name: "Google Customer Experience",
    role: "Full Stack Developer",
    skills: [
      "Node.js",
      "Express",
      "PostgreSQL",
      "GCP",
      "Microservices",
      "Monolithic Architecture",
      "Nexe",
      "Docker",
    ],
    client: "Google",
    employerKey: "accenture",
    points: [
      "Developed all backend APIs from scratch, integrating with GCP buckets and implementing custom role management.",
      "Boosted application performance by 50% by transitioning from monolithic to microservice architecture, earning MVP awards.",
      "Increased system reliability by 40% by optimizing PostgreSQL queries and enhancing the application's scalability.",
      "Contributed to GCP deployment, improving availability and ensuring smooth operation for marketing managers.",
      "Streamlined deployment using Docker, ensuring quick and reliable production builds.",
    ],
    link: "https://www.accenture.com/in-en/services/software-platforms/accenture-google-cloud-business-group",
  },
  {
    id: 6,
    name: "CHUBB: Mergers & Acquisitions",
    role: "Full Stack Developer",
    skills: [
      "Node.js",
      "Express",
      "Angular",
      "PostgreSQL",
      "Azure",
      "Custom Algorithms",
      "Docker",
    ],
    client: "CHUBB",
    employerKey: "accenture",
    points: [
      "Enhanced application infrastructure using Node.js, improving performance by 40% and scalability by 50%.",
      "Reduced deployment times by 35% using Azure for seamless production transitions, lowering operational costs by 20%.",
      "Optimized UI/UX by building responsive Angular components, boosting user engagement by 20% and improving interface usability by 30%.",
      "Implemented custom algorithms to automate deal review processes, enhancing efficiency for brokers and reducing manual efforts.",
      "Fixed critical bugs left by previous developers, ensuring smooth operations and on-time feature delivery.",
    ],
    link: "https://www.chubb.com/us-en/business-insurance/industries/mergers-acquisitions-insurance.html",
  },
];
